name: 修改微信步数

on:
  workflow_dispatch:
  schedule:
    # 每天早上 6 点运行 script1.py
    - cron: '0 10 * * *'
    # 每天中午 12 点运行 script2.py
    - cron: '7 0 * * *'
  push:  # 在推送时触发
  pull_request:  # 在拉取

jobs: 
  ChangBuShu: 
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        
    - name: 安装环境
      run: pip install -r ./requirements.txt
      
    - name: 修改早上步数
      if: github.event.schedule == '7 0 * * *'
      run: python changebushu_Actionday.py
      env:
        USER_PHONE: ${{ secrets.USER_PHONE }}
        USER_PWD: ${{ secrets.USER_PWD }}
        STEP: ${{ secrets.STEP }}
        STEP_MIN: ${{ secrets.STEP_MIN }}
        STEP_MAX: ${{ secrets.STEP_MAX }}

    - name: 修改晚上步数
      if: github.event.schedule == '0 10 * * *'
      run: python changebushu_Actionnight.py
      env:
        USER_PHONE: ${{ secrets.USER_PHONE }}
        USER_PWD: ${{ secrets.USER_PWD }}
        STEP: ${{ secrets.STEP }}
        STEP_MIN: ${{ secrets.STEP_MIN }}
        STEP_MAX: ${{ secrets.STEP_MAX }}

    - name: 手动修改步数
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: python changebushu_Action.py
      env:
        USER_PHONE: ${{ secrets.USER_PHONE }}
        USER_PWD: ${{ secrets.USER_PWD }}
        STEP: ${{ secrets.STEP }}
        STEP_MIN: ${{ secrets.STEP_MIN }}
        STEP_MAX: ${{ secrets.STEP_MAX }}
      
